services:
  db:
    image: postgres:latest
    container_name: chooser-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5454:5432'
    volumes:
      - chooser-db-volume:/var/lib/postgresql/data
volumes:
  chooser-db-volume:
    name: chooser-db-volume
